[[task]]
  id = "dev"
  type = "long"
  description = "Run the Go application in development mode."
  dependencies = ["start"]
  cmd = """
    echo "Running development mode..."
    while true; do sleep 1; done
  """

[[task]]
  id = "start"
  type = "short"
  description = "Run the binary."
  dependencies = ["build"]
  watch = ["bin/app"]
  cmd = """
    ./bin/app
  """

[[task]]
  id = "build"
  type = "short"
  description = "Build the binary for the Go application."
  watch = ["**/*.go"]
  cmd = """
    go build -o ./bin/app ./cmd/...
  """

[[task]]
  id = "test"
  type = "short"
  description = "Run all Go tests."
  cmd = """
    go test ./...
    echo "Testing complete."
  """

[[task]]
  id = "clean"
  type = "short"
  description = "Remove the binary and clean the Go test and module cache."
  cmd = """
    set -x

    rm -rf ./bin
    go clean -testcache
    go clean -modcache
  """

#-------------------------------------------------------------------------------
#  Go Test Variants
#-------------------------------------------------------------------------------

[[task]]
  id = "test-vv"
  description = "Run go tests wuth verbose output"
  type = "short"
  cmd = """
    go test -v ./...
  """

[[task]]
  id = "test-rr"
  description = "Run go tests with race detection"
  type = "short"
  cmd = """
    go test -race ./...
  """

[[task]]
  id = "test-cc"
  description = "Run go tests with coverage"
  type = "short"
  cmd = """
    go test -coverprofile=reports/coverage.out ./...
    go tool cover -html=reports/coverage.out -o reports/coverage.html
  """